### ISSUE TITLE
ssr xclip 报错

### ISSUE THREAD

**Issue by RioHsc** [the0demiurge/CharlesScripts#24]
请问正确的用法是什么😂, 弄半天没弄明白, 使用这个指令后貌似 config.json 这个文件会被删除
![Screenshot_20181211-004848.png](https://i.loli.net/2018/12/11/5c0e991cb05a7.png)

**Comment by RioHsc** [comment]
不能用 ssr://****** 的方式来导入吗?

**Comment by the0demiurge** [comment]
不能

RioHsc <notifications@github.com>于2018年12月11日 周二下午1:57写道：
